name: spartan
description: "The companion app for Spartan ensures seamless connectivity, allowing parents to monitor and control the baby bed effortlessly. It provides real-time updates on the baby's sleep status, personalized settings for optimal comfort, and educational resources for parents, fostering confidence and security in their baby's sleep routine."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.29.0
  google_sign_in: ^6.2.1
  go_router: ^13.2.4
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  simple_fontellico_progress_dialog: ^0.3.0
  provider: ^6.1.2
  curved_labeled_navigation_bar: ^2.0.2
  flutter_facebook_auth: ^6.0.4
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  dio: ^5.4.3+1
  awesome_notifications: ^0.8.2
  intl: ^0.18.1
  voice_message_package: ^2.2.1
  reaction_askany: ^0.1.2
  swipe_to: ^1.0.6
  googleapis_auth: ^1.6.0
  awesome_notifications_core: ^0.9.3
  emoji_picker_flutter: ^2.2.0
  shimmer: ^3.0.0
  rxdart_ext: ^0.2.9
  webview_flutter: ^4.7.0
  file_picker: ^8.0.3
  chat_composer: ^1.0.3
  qr_code_scanner: ^1.0.1
  popover: ^0.3.0
  motion_toast: ^2.9.1
  http: ^1.2.1
  textfield_tags: ^3.0.1
  sn_progress_dialog: ^1.1.4
  image_picker_for_web: ^3.0.4
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/icons/
    - assets/icons/home/
    - assets/icons/profile/
    - assets/icons/ticks/
