// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6zbl4WpKBGYkh51JGHzO59zZyXITT28',
    appId: '1:756938937223:android:bee210966e3d1d8e74f922',
    messagingSenderId: '756938937223',
    projectId: 'spartan-3b328',
    storageBucket: 'spartan-3b328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAEFJQEMDS7SuP_v8HaGPdfNM2L4RXRyk',
    appId: '1:756938937223:ios:2548cdc97569abed74f922',
    messagingSenderId: '756938937223',
    projectId: 'spartan-3b328',
    storageBucket: 'spartan-3b328.appspot.com',
    androidClientId: '756938937223-i8t4rbveoq65d17am1qeps7lm3cctal7.apps.googleusercontent.com',
    iosClientId: '756938937223-6qnuq3kogmff6hk92173tlddqrjm8nsq.apps.googleusercontent.com',
    iosBundleId: 'com.spartan.app',
  );

}